CREATE SCHEMA IF NOT EXISTS ANYCOMPANY_LAB.ANALYTICS;

USE DATABASE ANYCOMPANY_LAB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.SALES_ENRICHED AS
SELECT
    TRANSACTION_ID,
    TRANSACTION_DATE,
    YEAR(TRANSACTION_DATE) AS SALES_YEAR,
    MONTH(TRANSACTION_DATE) AS SALES_MONTH,
    QUARTER(TRANSACTION_DATE) AS SALES_QUARTER,
    DATE_TRUNC('MONTH', TRANSACTION_DATE) AS SALES_MONTH_DATE,
    REGION,
    PAYMENT_METHOD,
    ENTITY,
    AMOUNT,
    CASE 
        WHEN AMOUNT < 100 THEN 'LOW'
        WHEN AMOUNT < 1000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SALE_AMOUNT_BAND,
    CASE
        WHEN MONTH(TRANSACTION_DATE) IN (12, 1, 2) THEN 'WINTER'
        WHEN MONTH(TRANSACTION_DATE) IN (3, 4, 5) THEN 'SPRING'
        WHEN MONTH(TRANSACTION_DATE) IN (6, 7, 8) THEN 'SUMMER'
        ELSE 'AUTUMN'
    END AS SEASON,
    CASE 
        WHEN AMOUNT >= 1000 THEN 1
        ELSE 0
    END AS HIGH_VALUE_SALE_FLAG
FROM ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS
WHERE UPPER(TRANSACTION_TYPE) = 'SALE';


CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.CUSTOMER_SEGMENTS AS
SELECT
    CUSTOMER_ID,
    NAME,
    DATE_OF_BIRTH,
    GENDER,
    REGION,
    COUNTRY,
    CITY,
    MARITAL_STATUS,
    ANNUAL_INCOME,
    DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    CASE
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 25 THEN '18-24'
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 35 THEN '25-34'
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 50 THEN '35-49'
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 65 THEN '50-64'
        ELSE '65+'
    END AS AGE_GROUP,
    CASE
        WHEN ANNUAL_INCOME < 30000 THEN 'LOW INCOME'
        WHEN ANNUAL_INCOME < 70000 THEN 'MIDDLE INCOME'
        WHEN ANNUAL_INCOME < 120000 THEN 'UPPER MIDDLE INCOME'
        ELSE 'HIGH INCOME'
    END AS INCOME_SEGMENT
FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_DEMOGRAPHICS;


CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.CAMPAIGNS_ENRICHED AS
SELECT
    CAMPAIGN_ID,
    CAMPAIGN_NAME,
    CAMPAIGN_TYPE,
    PRODUCT_CATEGORY,
    TARGET_AUDIENCE,
    START_DATE,
    END_DATE,
    DATE_TRUNC('MONTH', START_DATE) AS CAMPAIGN_MONTH_DATE,
    REGION,
    BUDGET,
    REACH,
    CONVERSION_RATE,
    DATEDIFF('DAY', START_DATE, END_DATE) + 1 AS CAMPAIGN_DURATION_DAYS,
    CASE 
        WHEN REACH > 0 THEN BUDGET / REACH
        ELSE NULL
    END AS COST_PER_REACH,
    ROUND(REACH * CONVERSION_RATE, 0) AS ESTIMATED_CONVERSIONS
FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS;


CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.PROMOTIONS_ENRICHED AS
SELECT
    PROMOTION_ID,
    PRODUCT_CATEGORY,
    PROMOTION_TYPE,
    DISCOUNT_PERCENTAGE,
    START_DATE,
    END_DATE,
    DATE_TRUNC('MONTH', START_DATE) AS PROMO_MONTH_DATE,
    REGION,
    DATEDIFF('DAY', START_DATE, END_DATE) + 1 AS PROMOTION_DURATION_DAYS,
    CASE
        WHEN DISCOUNT_PERCENTAGE < 0.10 THEN 'LOW'
        WHEN DISCOUNT_PERCENTAGE < 0.20 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS PROMOTION_INTENSITY
FROM ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN;


CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.REVIEWS_AGGREGATED AS
SELECT
    DATE_TRUNC('MONTH', REVIEW_DATE) AS REVIEW_MONTH_DATE,
    PRODUCT_CATEGORY,
    COUNT(*) AS NB_REVIEWS,
    AVG(RATING) AS AVG_RATING
FROM ANYCOMPANY_LAB.SILVER.PRODUCT_REVIEWS
GROUP BY 1, 2;


CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.INVENTORY_AGGREGATED AS
SELECT
    REGION,
    PRODUCT_CATEGORY,
    COUNT(*) AS NB_PRODUCTS_IN_STOCK,
    AVG(CURRENT_STOCK) AS AVG_CURRENT_STOCK,
    AVG(REORDER_POINT) AS AVG_REORDER_POINT,
    AVG(LEAD_TIME) AS AVG_LEAD_TIME,
    SUM(CASE WHEN CURRENT_STOCK <= REORDER_POINT THEN 1 ELSE 0 END) AS STOCK_ALERT_COUNT
FROM ANYCOMPANY_LAB.SILVER.INVENTORY
GROUP BY 1, 2;


CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.SUPPLIER_INVENTORY_SUMMARY AS
SELECT
    s.REGION,
    s.PRODUCT_CATEGORY,
    COUNT(DISTINCT s.SUPPLIER_ID) AS NB_SUPPLIERS,
    AVG(s.LEAD_TIME) AS AVG_SUPPLIER_LEAD_TIME,
    AVG(s.RELIABILITY_SCORE) AS AVG_RELIABILITY_SCORE,
    COUNT_IF(s.QUALITY_RATING = 'A') AS NB_QUALITY_A_SUPPLIERS,
    i.NB_PRODUCTS_IN_STOCK,
    i.AVG_CURRENT_STOCK,
    i.AVG_LEAD_TIME AS AVG_INVENTORY_LEAD_TIME,
    i.STOCK_ALERT_COUNT
FROM ANYCOMPANY_LAB.SILVER.SUPPLIER_INFORMATION s
LEFT JOIN ANYCOMPANY_LAB.ANALYTICS.INVENTORY_AGGREGATED i
    ON s.REGION = i.REGION
   AND s.PRODUCT_CATEGORY = i.PRODUCT_CATEGORY
GROUP BY
    s.REGION,
    s.PRODUCT_CATEGORY,
    i.NB_PRODUCTS_IN_STOCK,
    i.AVG_CURRENT_STOCK,
    i.AVG_LEAD_TIME,
    i.STOCK_ALERT_COUNT;


CREATE OR REPLACE TABLE ANYCOMPANY_LAB.ANALYTICS.MARKETING_PERFORMANCE_MART AS
WITH sales_monthly AS (
    SELECT
        SALES_MONTH_DATE AS MONTH_DATE,
        REGION,
        COUNT(*) AS NB_SALES,
        SUM(AMOUNT) AS TOTAL_SALES_AMOUNT,
        AVG(AMOUNT) AS AVG_SALES_AMOUNT,
        SUM(HIGH_VALUE_SALE_FLAG) AS NB_HIGH_VALUE_SALES
    FROM ANYCOMPANY_LAB.ANALYTICS.SALES_ENRICHED
    GROUP BY 1, 2
),
campaign_monthly AS (
    SELECT
        CAMPAIGN_MONTH_DATE AS MONTH_DATE,
        REGION,
        COUNT(*) AS NB_CAMPAIGNS,
        SUM(BUDGET) AS TOTAL_CAMPAIGN_BUDGET,
        SUM(REACH) AS TOTAL_CAMPAIGN_REACH,
        AVG(CONVERSION_RATE) AS AVG_CONVERSION_RATE,
        SUM(ESTIMATED_CONVERSIONS) AS TOTAL_ESTIMATED_CONVERSIONS
    FROM ANYCOMPANY_LAB.ANALYTICS.CAMPAIGNS_ENRICHED
    GROUP BY 1, 2
),
promo_monthly AS (
    SELECT
        PROMO_MONTH_DATE AS MONTH_DATE,
        REGION,
        COUNT(*) AS NB_PROMOTIONS,
        AVG(DISCOUNT_PERCENTAGE) AS AVG_DISCOUNT_PERCENTAGE
    FROM ANYCOMPANY_LAB.ANALYTICS.PROMOTIONS_ENRICHED
    GROUP BY 1, 2
)
SELECT
    COALESCE(s.MONTH_DATE, c.MONTH_DATE, p.MONTH_DATE) AS MONTH_DATE,
    COALESCE(s.REGION, c.REGION, p.REGION) AS REGION,
    COALESCE(s.NB_SALES, 0) AS NB_SALES,
    COALESCE(s.TOTAL_SALES_AMOUNT, 0) AS TOTAL_SALES_AMOUNT,
    COALESCE(s.AVG_SALES_AMOUNT, 0) AS AVG_SALES_AMOUNT,
    COALESCE(s.NB_HIGH_VALUE_SALES, 0) AS NB_HIGH_VALUE_SALES,
    COALESCE(c.NB_CAMPAIGNS, 0) AS NB_CAMPAIGNS,
    COALESCE(c.TOTAL_CAMPAIGN_BUDGET, 0) AS TOTAL_CAMPAIGN_BUDGET,
    COALESCE(c.TOTAL_CAMPAIGN_REACH, 0) AS TOTAL_CAMPAIGN_REACH,
    COALESCE(c.AVG_CONVERSION_RATE, 0) AS AVG_CONVERSION_RATE,
    COALESCE(c.TOTAL_ESTIMATED_CONVERSIONS, 0) AS TOTAL_ESTIMATED_CONVERSIONS,
    COALESCE(p.NB_PROMOTIONS, 0) AS NB_PROMOTIONS,
    COALESCE(p.AVG_DISCOUNT_PERCENTAGE, 0) AS AVG_DISCOUNT_PERCENTAGE
FROM sales_monthly s
FULL OUTER JOIN campaign_monthly c
    ON s.MONTH_DATE = c.MONTH_DATE
   AND s.REGION = c.REGION
FULL OUTER JOIN promo_monthly p
    ON COALESCE(s.MONTH_DATE, c.MONTH_DATE) = p.MONTH_DATE
   AND COALESCE(s.REGION, c.REGION) = p.REGION;


CREATE OR REPLACE VIEW ANYCOMPANY_LAB.ANALYTICS.V_MARKETING_PERFORMANCE AS
SELECT
    MONTH_DATE,
    REGION,
    NB_SALES,
    TOTAL_SALES_AMOUNT,
    AVG_SALES_AMOUNT,
    NB_HIGH_VALUE_SALES,
    NB_CAMPAIGNS,
    TOTAL_CAMPAIGN_BUDGET,
    TOTAL_CAMPAIGN_REACH,
    AVG_CONVERSION_RATE,
    TOTAL_ESTIMATED_CONVERSIONS,
    NB_PROMOTIONS,
    AVG_DISCOUNT_PERCENTAGE
FROM ANYCOMPANY_LAB.ANALYTICS.MARKETING_PERFORMANCE_MART;